export const STORAGE_KEY_EFFECT_VOLUME = "STORAGE_KEY_EFFECT_VOLUME";

export const STORAGE_KEY_MUSIC_VOLUME = "STORAGE_KEY_MUSIC_VOLUME";

export const STORAGE_KEY_EFFECT_SWITCH = "STORAGE_KEY_EFFECT_SWITCH";

export const STORAGE_KEY_MUSIC_SWITCH = "STORAGE_KEY_MUSIC_SWITCH";

export const STORAGE_KEY_VIBRATE_PHONE = "STORAGE_KEY_VIBRATE_PHONE";

export const STORAGE_KEY_AUTO_FEED = "STORAGE_KEY_AUTO_FEED";

export const STORAGE_KEY_AUTO_LEARN = "STORAGE_KEY_AUTO_LEARN";

export const STORAGE_KEY_AUTO_WORK = "STORAGE_KEY_AUTO_WORK";