export enum EventName {
    EVENT_TEST = "EVENT_TEST",

    GAME_HEART_BEAT_ONE_MINUTE = "GAME_HEART_BEAT_ONE_MINUTE",

    E_WX_REWARD_VIDEO_AD_COMPLETE = "E_WX_REWARD_VIDEO_AD_COMPLETE", // 通知后端微信广告播放完毕
    E_WX_REWARD_VIDEO_AD_FINIDHED = "E_WX_REWARD_VIDEO_AD_FINIDHED", // 微信广告跳过或收到后端反馈
    E_WX_REWARD_VIDEO_AD_BREAKED = "E_WX_REWARD_VIDEO_AD_BREAKED", // 微信广告中断
    E_WX_REWARD_VIDEO_AD_ERROR = "E_WX_REWARD_VIDEO_AD_ERROR", // 微信广告错误

    E_PROPERTY_VALUE_CHANGED = "E_PROPERTY_VALUE_CHANGED",
    E_AGE_CHANGED = "E_AGE_CHANGED",
    E_MONEY_CHANGED = "E_MONEY_CHANGED",

    E_FRIENDS_LIST_CHANGED = "E_FRIENDS_LIST_CHANGED",
    E_FRIENDS_APPLY_LIST_CHANGED = "E_FRIENDS_APPLY_LIST_CHANGED",

    E_TUTELAGE_SWITCH_CHANGED = "E_TUTELAGE_SWITCH_CHANGED",
    E_TUTELAGE_FEED_CHANGED = "E_TUTELAGE_FEED_CHANGED",
    E_TUTELAGE_WORK_CHANGED = "E_TUTELAGE_WORK_CHANGED",
    E_TUTELAGE_STUDY_CHANGED = "E_TUTELAGE_STUDY_CHANGED",

    E_GROWTH_RATE_CHANGED = "E_GROWTH_RATE_CHANGED",
    // E_EXP_CHANGED = "E_EXP_CHANGED",

    E_SUBJECT_LEARNED = "E_SUBJECT_LEARNED",
    E_SCHOOL_TIMER_HANDLE = "E_SCHOOL_TIMER_HANDLE",

    E_ACTION_CHANGED = "E_ACTION_CHANGED",

    E_JOB_TIMER_HANDLE = "E_JOB_TIMER_HANDLE",
    E_JOB_COMPLETED = "E_JOB_COMPLETED",

    E_ITEM_USED = "E_ITEM_USED",

    E_PLAYER_ITEM_NUM_CHANGED = "E_PLAYER_ITEM_NUM_CHANGED",

    E_ACTOR_LISTEN_STATUS = "E_ACTOR_LISTEN_STATUS",
    
    E_PURCHASE_SHOP_GOOD_BACK = "E_PURCHASE_SHOP_GOOD_BACK",
    E_TUTELAGE_ITEM_SELECTED = "E_TUTELAGE_ITEM_SELECTED",
}
